apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbit-server
  labels:
    app: qbit-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbit
      tier: app
  template:
    metadata:
      name: qbit-pod-server
      labels:
        app: qbit
        tier: app
    spec:
      containers:
        - name: qbit-server
          image: qasim683/qbit-server4
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: qbit-secret
                  key: MYSQL_HOST
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: qbit-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: qbit-secret
                  key: MYSQL_USER     
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qbit-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qbit-secret
                  key: MYSQL_ROOT_PASSWORD 
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: qbit-secret
                  key: MYSQL_PORT
            - name: DJ_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: dj-config
                  key: DJ_ALLOWED_HOSTS
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: dj-config
                  key: DEBUG
            - name: DJ_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: dj-config
                  key: DJ_SECRET_KEY
